### PR TITLE
Adding autodoc to sphinx config.

### PR DESCRIPTION
**Pull request by jbohren**

### CODE REVIEW

**Comment by jbohren** [comment]
Is this all that's needed to actually have documentation for things like this?

http://docs.ros.org/hydro/api/tf_conversions/html/python/

**Comment by jbohren** [comment]
To answer my own question: *yes*

This does enable sphinx documentation to use automodules.

**Comment by jack-oquin** [comment]
Thanks for the patch, Jon. Looks good to me.

**Comment by jbohren** [comment]
Does rosdoc_lite need to get released before this affects the stuff on docs.ros.org?

**Comment by jack-oquin** [comment]
No, but I plan to release it anyway, at least to Indigo. It needs to be released for it to work out-of-the-box when running on your own development system. 

Do you need or want it on Hydro?

**Comment by jbohren** [comment]
> Do you need or want it on Hydro?

Yeah, that would be great if it's not too much trouble.

**Comment by jack-oquin** [comment]
No trouble. 

I normally would not make changes (except bug fixes) in a release that old, but since the build farm always picks up the latest version, it seems reasonable to keep the Hydro release in sync.

**Comment by jbohren** [comment]
@jack-oquin Any idea why the automodule stuff still isn't working? It worked when I ran it on my local machine.

**Comment by jack-oquin** [comment]
Perhaps the build farm does not have some packages installed that you do?

If so, and we can figure out what they are, we could maybe add them with ``<doc_depend>``.

**Pull request merged**
